spring.application.name=ResumeService


server.port = ${PORT:8084}
spring.datasource.url =DATABASE_URL
spring.datasource.username = DATABASE_USERNAME
spring.datasource.password = DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=TRACE

cloudinary.cloud-name=dgvxb2eun
cloudinary.api-key=696357819292935
cloudinary.api-secret=BJEPkNmwmaYk1WDRoxA1XI2o22c