spring.application.name=PartyService

server.port = 8082
spring.datasource.url =jdbc:postgresql://db.chsvlluuzkpnxebmowkm.supabase.co:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = Superelevation@99
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=TRACE

jwt.secret=MySuperSecretKeyForJWT-this-is-long-enough-i-belive-for-protection
jwt.expiration-ms=86400000
